### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by professor** [edmcman/cmu-ece-thesis-template#1]
I'd love to see how an Appendix should work with the sty file.

I tried the following, but the appendix did not show up well in the table of contents and was tacked on as an extra section in the last chapter.

....

\appendix
\section*{Appendix}
\chapter{Interview Transcriptions}
Test of appendix

\bibliographystyle{IEEEtran}
\bibliography{bibliography}

\backmatter

\end{document}

**Comment by edmcman** [comment]
I don't think this is specific to this style file... but try:

```
\chapter*{Appendix}
\section*{Interview Transcriptions}
```

**Comment by professor** [comment]
Thanks for your help. I learned something new about latex. I just sent a pull request on how I would expect an appendix to look
